### ISSUE TITLE
有没有办法自动识别要多发的包，现在这样麻木多发包不是太好吧

### ISSUE THREAD

**Issue by harrydleung** [snooda/net-speeder#1]
RT，ping一次反4次回来，windows上就更可怕了。。我怕大家用会拖累国际互联网

**Comment by snooda** [comment]
返4次并不是真的有4个应答包。
发一次ping，net-speeder会double成两个。
不丢包的情况下对端返回两个。
net-speeder内部再double一下，所以看起来是4个包，实际在网络上的只有两个。
至于为啥返回包也要内部double，是为了更快触发快速重传。

**Comment by harrydleung** [comment]
有人说在windows 下ttl值更大，会有更多包，是这样吗？（在学校没电脑测试😂）

**Comment by snooda** [comment]
理论上不会，这个跟ttl的大小无关的

**Comment by harrydleung** [comment]
哦。

**Comment by Bestoa** [comment]
@Halry TTL是我说的，但并不是说windows会多发包，而是88这个值不妥。
Windows 默认TTL是128，一般收到的时候是108左右，一般确实不会掉到88，但是。。。建议改成68

另外可以根据网卡类型去决定lenth，去掉COOKED宏。

**Comment by snooda** [comment]
@bestoa  收到，我后续会考虑修改这个值。

其实88只是个magic number而已。改大改小总会有人恰好到这个值。
net-speeder主要依赖的是向外发出包的ttl。收到包的ttl不太重要

**Comment by harrydleung** [comment]
@snooda我真的不明白bpf和cooked的意思。。。
还有，我用这个的话手机上流量会翻倍吗？

**Comment by frjalex** [comment]
@Halry 手机上应该不会翻倍流量。根据代码来判断，应该是服务器端double流量。

**Comment by jack2007** [comment]
@frjalex  手机端的流量肯定是两倍；
手机端的TCP协议栈收到重复报文后会丢弃掉，但是从运营商的计费系统来看，IP报文已经到了你的手机，流量肯定是要算你的；
