### ISSUE TITLE
这个工具难道不会双倍消耗网络流量和带宽资源么

### ISSUE THREAD

**Issue by Koishi-komeiji** [snooda/net-speeder#10]
手机连接用net-speeder的服务器，消耗流量不会x2么。
原本100M的连接，用了不会只有50M有效速度么。
如果是这样，那这个工具的意义是什么。
如果不是这样，求解答。

**Comment by sgqy** [comment]
http://www.snooda.com/read/324 作者博客说这是提高稳定性的，不过基本上是廉价vps专用了。
