### ISSUE TITLE
packet len:[52] actual write:[-1] err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted) ]

### ISSUE THREAD

**Issue by Facebooksx** [snooda/net-speeder#11]
screen里看到如下日志：
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
怎么解决？是不是netspeeder优化失败了？

**Comment by MiaoZhou** [comment]
同样出现这个提示

**Comment by apple601601601** [comment]
也是这个错误， CentOS 6 64bit

**Comment by harrydleung** [comment]
网卡选错了，还是不在root下？

**Comment by apple601601601** [comment]
找到原因了： VPS是OpenVZ架构的，编译的时候要加入-DCOOKED参数
Linux Cooked interface使用编译（venetX，OpenVZ）： sh build.sh -DCOOKED 已测试

**Comment by vagrant1991** [comment]
@apple601601601 并没效果，还是出错， 你测试通过吗？ 还是加了其他什么命令？

**Comment by iosmanthus** [comment]
一样，所以用着用着就会断...求解决

**Comment by oovz** [comment]
在issue里看看

**Comment by SherlockLee** [comment]
这个问题现在依然存在呢,作者说这个不影响使用可以暂时不用管

**Comment by snooda** [comment]
ovz下的话，少量这个错误不用管，不影响效果。
kvm的话，len后面是一个大于mtu的值，关闭tso即可
