### ISSUE TITLE
能不能过滤一下 PPTP 协议啊

### ISSUE THREAD

**Issue by x91270** [snooda/net-speeder#13]
好像会影响 PPTP 协议握手

**Comment by afc** [comment]
BPF过滤语法好像只支持ether, fddi, tr, wlan, ip, ip6, arp, rarp, decnet, tcp, udp这些语法

不过既然协议上过滤不了PPTP你可以考虑从端口上过滤掉PPTP

PPTP默认监听端口为1723, 你可以这么启动net_speeder:
```
./net_speeder venet0 "ip and not src port 1723"
```
这样就把IP协议并且源端口不是1723的IP数据报发双倍了 这样就过滤掉了PPTP协议

[BPF协议语法](https://biot.com/capstats/bpf.html)
