### ISSUE TITLE
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)

### ISSUE THREAD

**Issue by TangMonk** [snooda/net-speeder#15]
ubuntu 15.04， 运行后一直报错

**Comment by FateTestarossa** [comment]
因为你的网卡支持TOE，收到的TCP包是已经拼接好的，长度很可能超过MTU，raw发送并不会分片，当然发不出去，关掉你网卡的TOE就可以（Debian系列：ethtool -K your_interface_name tx off rx off），或者自行修改源码在发送时拆分数据包

**Comment by bao3** [comment]
@FateTestarossa 可是，用 ethtool 关了 tx rx 也不行，依然报错。。而且网上有好多人也这样，却从没人解决掉。

**Comment by FateTestarossa** [comment]
@bao3 是关gro<

**Comment by KyonCN** [comment]
求解决啊 我也一样的情况

**Comment by wangliang7730** [comment]
一样的情况,怎么破。

**Comment by wangliang7730** [comment]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
一样的问题，有谁能破。

**Comment by FateTestarossa** [comment]
@wangliang7730 关掉你网卡的GSO GRO(这俩一般都有 TSO LRO(如果有的话

**Comment by KyonCN** [comment]
我解决了 换内核 换版本 15.04下无解

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by snooda** [comment]
关闭tso即可，首页已更新方式
