### ISSUE TITLE
yum install libnet libpcap libnet-devel libpcap-devel     return error

### ISSUE THREAD

**Issue by weaming** [snooda/net-speeder#16]
yum install libnet libpcap libnet-devel libpcap-devel

then 

Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
- base: mirrors.linode.com
- epel: mirror.sfo12.us.leaseweb.net
- extras: mirrors.linode.com
- updates: mirrors.linode.com
  Error: xz compression not available

**Comment by weaming** [comment]
```
rm -rf /var/cache/yum/x86_64/6/epel
```

[serverfault.com](http://serverfault.com/questions/675802/xz-compression-not-available-yum-error-on-centos)
OK!

**Comment by fineday009** [comment]
@weaming  谢谢，我按照这个rm -rf /var/cache/yum/x86_64/6/epel，然后yum update
之后：
#安装epel：
rpm -ivh epel-release-6-8.noarch.rpm
#然后即可使用yum安装：
yum install libnet libpcap libnet-devel libpcap-devel
sh build.sh

全部顺利走完了流程。感谢
