### ISSUE TITLE
如何判断是否安装成功？运行后在windows下ping仍然返回单个数据包

### ISSUE THREAD

**Issue by fengshens** [snooda/net-speeder#17]

**Comment by m13253** [comment]
Windows 的 ping 是不行的。
实现算法不一样。
必须 Linux 或 OS X 的 ping。

**Comment by snooda** [comment]
如果执行时选择对ip加速。那么ping是有效的。如果只选择了对tcp加速。ping是看不出来的。只能用wireshark之类的工具观察。
因为ping是icmp协议

**Comment by osdebianly** [comment]
在linux 下，会有 带 dup 包返回，windows 确实没有

**Comment by snooda** [comment]
windows用工具也可以看到。只是ping命令没有打印dup的应答而已。

**Comment by cmdlet1** [comment]
其实可以 top 查看有没有net-speeder进程
或者 ps aux|grep net-speeder 查看运行时间，如果是0的话就是没运行

**Comment by NoAnyLove** [comment]
我有点晕，在Linux虚拟机上ping一下服务器，会返回4个包，其中3个显示`DUP!`，但是4个包中，有2个的ttl是44，有2个是68。所以到底重复的是几个包？

**Comment by osdebianly** [comment]
我的搬瓦工流量大一点就被封了， 现在不敢用了， 改用finalspeed+ shadowsocks，速度杠杠的！！ 就是至少要256M 内存

2016-05-30 13:07 GMT+08:00 NoAnyLove <notifications@github.com>:
