### ISSUE TITLE
（小白问题）怎么设置定时运行？

### ISSUE THREAD

**Issue by BarryBarrywu** [snooda/net-speeder#18]
已经成功在Bandwagon  Centos 6 x86_64 minimal 上安装成功，想在高分期的时候开启，正常时间段关闭证明操作？ 网上搜了几个教程都不成功。

**Comment by snooda** [comment]
高峰期和低峰期的判断标准是什么？
可以用crontab实现

**Comment by harrydleung** [comment]
用corntab，自己写个脚本好像就ok了

**Comment by BarryBarrywu** [comment]
国内时间晚上6点以后到夜间2点这样吧，国内数据流量大的时间段开启。 其他时间感觉开启也没啥效果，而且服务端又占用2倍流量。

可以告知具体的corntab脚本吗？Linux命令完全不熟悉。

**Comment by krizex** [comment]
如果对Linux完全不熟悉的话，要教会你使用crontab挺困难的，毕竟你还会遇到crobtan环境变量的坑。。。google下shell脚本还有crontab，半天时间应该能搞定你的需求了。加油！

**Comment by BarryBarrywu** [comment]
研究了下,已经设置.

//删除时区

# rm -rf /etc/localtime

//设置中国时区，成功后输入date，查看是否和电脑时间一致。

# ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

//安装crontabs服务

# yum -y install crontabs

//设置19:00开启net_speeder

# echo '0 19 \* \* \* root nohup /root/net_speeder venet0 "Your ip" >/dev/null 2>&1 &' >>/etc/crontab

//设置0:00关闭net_speeder

# echo "0 0 \* \* \* root killall net_speeder" >>/etc/crontab
