### ISSUE TITLE
频繁出现packet len:[2868] actual write:[-1] err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long) ]

### ISSUE THREAD

**Issue by harrydleung** [snooda/net-speeder#2]
RT

**Comment by snooda** [comment]
这个我看一下~多谢

**Comment by harrydleung** [comment]
不止这个，还有其他一些问题。
顺便支持下，在晚上高丢包的情况下终于能流畅刷g+。你这是开始继续这个项目了吗？

**Comment by snooda** [comment]
哈哈，最近会升级一下。有问题欢迎给我留言啊，我一起修一下

**Comment by harrydleung** [comment]
希望能做成底层，能智能点补发包，这样就不用那么多流量了，像锐速一样（vultr的日本节点才200g流量）。
另外，bpf是什么？

**Comment by PeterCxy** [comment]
这个我也会出现，但是实际上包也被双倍发送了

**Comment by quericy** [comment]
希望能智能发包+1....前些天在DigitalOcean上用了以后虽然提速妥妥的,但是没几天就被封VPS了ORZ....

**Comment by snooda** [comment]
@quericy 在考虑做了。提速效果虽好，也要低调啊。哈哈。对于发包重复这个机房目前在意的不多，因为tcp协议栈本身就是会重试的。但很多机房是不让长时间占用大带宽的（看y2b，下载之类的）

**Comment by harrydleung** [comment]
@snooda根本低调不了，简直就是提速神器，在家连720p都能看了

**Comment by consatan** [comment]
我有台虚拟机是 VirtualBox 下安装的 Debian 7，使用 sh build.sh 编译，运行的时候会提示大量的这个错误
packet len:[2868] actual write:[-1] err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long) ]
另一台同样系统的物理机就正常

**Comment by thefangbear** [comment]
@snooda 问几个问题哈。
1.这个不会影响TCP公平性么？大家都使用这个会不会拖跨国际网络？从V2EX上过来的，看到很多人都在骂netspeeder和锐速自私。
2.用了这个服务器流量double我知道，但是我想知道在中等延迟（有时候可以跑满带宽）情况下会不会反而拖慢网络速度？毕竟一次发两遍，时间久了反而容易制造堵塞吧，拖慢自己的网速吧。。。
3.有人说用了这个带宽最多只能跑到原来的二分之一（发两遍包的缘故），这个是真的么？

对TCP不甚了解，还请包涵，多多指教～

谢谢

**Comment by swmjjy** [comment]
CA的VPS，用或不用net_speeder单线程下载都过不了100KB/s，但用VPN连接到VPS以后不开net_speeder单线程下载能上2MB/s，求解
PS：同样大量出现楼主所说的错误

**Comment by yuko1225** [comment]
@frjalex netspeeder某种程度上是把TCP当UDP玩 是有公平性问题的。锐速分模式，默认模式下，锐速只是利用了自己应该利用的带宽。另一个模式是最大化模式（maxmode），确实会对带宽有公平性影响，默认是不开启的。

另外net-speeder因为是无脑多倍，2、3的情况都会出现，而且我都遇到过。这点锐速要好，锐速不是多倍发包，除了某些情况下会对低延迟线路（RTT＜20ms）有影响（可以通过修改配置规避低延迟加速），对于多数应用都是正面影响，且不开maxmode时，不会出现高于0.1%的带宽开销

**Comment by tuxzz** [comment]
可以试试编译时加上-DCOOKED
我在openvz机子测试时这样就不报错了

**Comment by FateTestarossa** [comment]
因为你的网卡支持TOE，收到的TCP包是已经拼接好的，长度很可能超过MTU，raw发送并不会分片，当然发不出去，关掉你网卡的TOE就可以（Debian系列：ethtool -K your_interface_name tx off rx off），或者自行修改源码在发送时拆分数据包

**Comment by holmesian** [comment]
出现 `libnet_write_raw_ipv4(): -1 bytes written (Message too long)` 错误可以在编译的时候./build -DCOOKED 解决

**Comment by FateTestarossa** [comment]
加DCOOKED仅限OpenVZ这种交给母机内核处理的情况，其他虚拟化平台完全无用，修改源码在发包时拆分才是彻底的解决方法

**Comment by vagrant1991** [comment]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by hldh214** [comment]
packet len:[60] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by rightpeter** [comment]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)

**Comment by oovz** [comment]
所谓的公平性问题，其实不如讨论IDC的公平性。
流量限制就是为了不让你能持续跑满，那你既然能持续跑满，除非TOS标出，要么是没有问题的。
运营商买的国际带宽也是实打实的那么多，你买的流量也是那么多。那backbone或者idc超售，指望用户不跑满，难道还要用户承担道德责任吗？@frjalex

**Comment by nanqinlang** [comment]
话说作者大大还会更新这个吗 @snooda

**Comment by nanqinlang** [comment]
@FateTestarossa 大佬你好
请问如果要 ”自行修改源码在发送时拆分数据包“ 的话，应该怎么修改源码啊。。。

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by snooda** [comment]
更新了readme，kvm机器下关闭tso即可。
ethtool -K 网卡 tso off

**Comment by liuxyon** [comment]
> 更新了readme，kvm机器下关闭tso即可。
> ethtool -K 网卡 tso off

这个在unbutu 19.0.4 kvm 不起作用,仍然错误提示
