### ISSUE TITLE
如何监控net-speeder进程，使其进程不在时自动重启

### ISSUE THREAD

**Issue by wclmgcd** [snooda/net-speeder#20]
我的net-speeder安装好后，有明显的效果，但就是进程有时无原因中断，有办法监控其进程，没进程时就自动重启?

**Comment by osdebianly** [comment]
- 使用supervisor,设置为自启动
- 使用定时脚本每分钟检查

**Comment by snooda** [comment]
ovz下把文件和文件夹重命名成其他名字，已知有厂商会按名字kill。
