### ISSUE TITLE
请求作者能够排除PPTP端口加速 

### ISSUE THREAD

**Issue by mucunmjin** [snooda/net-speeder#22]
请求作者能够排除PPTP端口加速 
谢谢。
或者启动命令里面可以加什么参数 排除吗。

**Comment by klzsysy** [comment]
这个很简单 ./net_speeder venet0 'tcp and ! tcp port 1723'
跟tcpdump的规则是一样的

**Comment by sky0014** [comment]
配合ss效果比较好，如果还想连pptp的话，可以看我的文章
[解决net-speeder与pptp不兼容的问题](http://www.cnblogs.com/DarkMaster/p/5517641.html)

**Comment by klzsysy** [comment]
@sky0014  是 ./netspeeder venet0 "tcp and ! tcp port  1723"
而你是你写的 ./netspeeder venet0 "tcp and tcp port ! 1723"
这个语法是有区别的

**Comment by sky0014** [comment]
@klzsysy 可以稍加解释下吗，谢谢。
我开始是用tcp and ! tcp port 1723的，发现不行我才换了下试试。

**Comment by klzsysy** [comment]
@sky0014 这里用的是BPF过滤器规则
"tcp and ! tcp port 1723" 表示 （tcp协议 与 （非 tcp 端口1723）） ，就是除了1723端口之外的所有TCP会话。如果你还想排除某端口可以在后面加上 "and ! _protocol_ xxx"  这里protocol可以是tcp或者udp。
具体语法可以 google "bpf规则"

**Comment by sky0014** [comment]
@klzsysy 好的，感谢！
