### ISSUE TITLE
在网卡支持TOE的情况下会有严重的问题

### ISSUE THREAD

**Issue by FateTestarossa** [snooda/net-speeder#23]
在网卡支持TOE的情况下会有严重的问题，libpcap收到的包是已经拼接好的 很大可能超过mtu导致无法发送，而多数VPS都是支持TOE的网卡

**Comment by yalog** [comment]
我测试，貌似数据超长后是没有被正常发送的。。
不知道@FateTestarossa 有没有啥好的解决方法？

**Comment by FateTestarossa** [comment]
最简单的解决方法是关掉网卡的checksum (openvz无效 不过openvz加个dcooked编译就行了
会降低性能 但VPS配置不是太低的话并没什么可见影响

**Comment by yalog** [comment]
我是关闭了网卡的TSO/GSO功能搞定的。。

然后用tcpdump抓包发现一个问题，就是复制包的延时很大，我收到的复制包基本得延迟1s。而我RTT很小，<100ms，那么这个复制发送包的机制岂不是没有啥效果了？

或者还是我搞错哪里了，为什么这么慢？请教！@FateTestarossa

**Comment by wclmgcd** [comment]
@yalog 关闭网卡的TSO / GSO功能，如何关闭？什么命令？在下小白，希望详细写出来，vps是版瓦工

**Comment by yalog** [comment]
可以看看这个blog
http://seitran.com/2015/04/13/01-gso-gro-lro/

**Comment by snooda** [comment]
关闭tso即可

**Comment by snooda** [comment]
复制包延迟1s的问题已经在最新版修复了
