### ISSUE TITLE
正常编译，开始执行就卡住了。

### ISSUE THREAD

**Issue by zorroforever** [snooda/net-speeder#29]
执行命令如下
sudo ./net_speeder eth0 "ip"

屏幕显示如下
Device: eth0
Filter rule: ip
ethernet header len:[14](14:normal, 16:cooked)
init pcap
init libnet
然后就么有然后了，这个怎么办呀？
环境是centos7 x64

**Comment by farruhtursun** [comment]
同样的问题
[root@vultr net-speeder-master]# ./net_speeder eth0 "ip"
Device: eth0
Filter rule: ip
ethernet header len:[14](14:normal, 16:cooked)
init pcap
init libnet

**Comment by farruhtursun** [comment]
我后来发现其实已经在运行了，你用top命令看看

**Comment by zorroforever** [comment]
当时可能后面是运行起来了，
可是vps供应商马上侦测到了异常，然后把我的服务冻结了。
我后面联系客服保证不再使用类似工具以后才解冻的。
以后还是老老实实的吧，哎

**Comment by farruhtursun** [comment]
我是还没被发现，昨晚开始用的

**Comment by isnowify** [comment]
same issue

**Comment by snooda** [comment]
正常的。本身就是常驻进程
