### ISSUE TITLE
如何在bangwagon的Debian 7.0 x86下安装net_speeder?

### ISSUE THREAD

**Issue by lovestudygithub** [snooda/net-speeder#3]
如何在bangwagon的Debian 7.0 x86下安装net_speeder?

**Comment by harrydleung** [comment]
自己编译呀，运行 ./build.sh -DCOOKED，生成的net_speeder运行即可

**Comment by snooda** [comment]
可以参照README里面debian/ubuntu安装方法安装libpcap和libnet，然后按@Halry的方式编译执行即可

**Comment by WAL2143739** [comment]
小白比较多，他们希望有直接复制粘贴的教程。比较了解Linux的人不是很多。
