### ISSUE TITLE
安装完以后使用FTP上传数据速度被限制了

### ISSUE THREAD

**Issue by zhanggaoxuan** [snooda/net-speeder#30]
安装完以后使用FTP上传数据速度被限制了，被限制到了50KB，是net-speeder的原因么

**Comment by m13253** [comment]
如果原来恰好是 100KB 的话，有可能是……

**Comment by zhanggaoxuan** [comment]
原来的不是100KB。。我记得是比100KB高

**Comment by m13253** [comment]
那就是你网络提供商的锅啦。

**Comment by zhanggaoxuan** [comment]
不像= =因为我就是供应商的员工，我想问Net-speeder有没有设置限速的功能= =

**Comment by m13253** [comment]
> 不像= =因为我就是供应商的员工，我想问Net-speeder有没有设置限速的功能= =

那我就不知道了，等原作者出来回答吧。应该是没有的。

**Comment by zhanggaoxuan** [comment]
好吧 = =哎

**Comment by snooda** [comment]
没有限速。看看是不是软件或哪里的问题吧

**Comment by zhanggaoxuan** [comment]
好吧= =话说能不能增加个设定限速功能，这样不至于把流量跑的飞起。。。

**Comment by snooda** [comment]
哈哈。。可以加一个速度达到一定速度不再加速的feature。

**Comment by zhanggaoxuan** [comment]
嗯嗯，对= =因为我发现我的这个VPS，开了net-speeder以后，ftp上传是50kb左右，关了net-speeder以后ftp上传是1Mb/s左右，很蛋疼啊。。。。。

**Comment by suixinio** [comment]
我同样也遇到了上传降速这个问题。
我的解决方案是使用bpf规则只复制本机发出的包

例如↓：
`./net_speeder venet0 "tcp and src host 本机 IP 地址" `
希望对你也有所帮助
