### ISSUE TITLE
./net_speeder eth0 198.199.100.x 出现filter rule err:[198.199.100.x ][syntax error]

### ISSUE THREAD

**Issue by kkangkaik** [snooda/net-speeder#31]
root@kk:/tmp/net-speeder-master# ./net_speeder eth0 198.199.100.x
Device: eth0
Filter rule: 198.199.100.x
ethernet header len:[14](14:normal, 16:cooked)
init pcap
init libnet
filter rule err:[198.199.100.70][syntax error]

**Comment by VincentSit** [comment]
./net_speeder venet0 "ip"

这一句你需要替换的只有你的网卡名称， “ip” 不是要你替换的.
