### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by fsgmhoward** [snooda/net-speeder#33]
```
packet len:[64] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
```

OpenVZ, Ubuntu 14.04 x86_64

**Comment by oovz** [comment]
同问

**Comment by GOUKI9999** [comment]
packet len:[17664] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
问题同上

**Comment by XuYankang** [comment]
问题同上

**Comment by eromoe** [comment]
问题同上， 搬瓦工512
你们是不是也是搬瓦工？？？

**Comment by swlfigo** [comment]
问题同上。搬瓦工

**Comment by huangcong12** [comment]
请问大家都解决了吗？同问题。

**Comment by pexcn** [comment]
试试

``` bash
ethtool -K venet0 tx off
ethtool -K venet0 rx off
ethtool -K venet0 gso off
ethtool -K venet0 gro off
```

**Comment by eromoe** [comment]
@pexcn 
这几行是什么意思？

**Comment by pexcn** [comment]
引用该项目其他issues的，关闭网卡TOE功能，但是我没用过，我没遇到这错误。

**Comment by eromoe** [comment]
关闭了还是一样错。。。你是ubuntu么？
为啥隔壁 搬瓦工 都运行没问题。。。

**Comment by pexcn** [comment]
我用debian

**Comment by winer632** [comment]
遇到同样的问题

**Comment by winer632** [comment]
Linux Cooked interface使用编译（venetX，OpenVZ）：

sh build.sh -DCOOKED
普通网卡使用编译（Xen，KVM，物理机）：

sh build.sh

版瓦工的使用sh build.sh -DCOOKED编译就OK了。不要谢我，我是红领巾

**Comment by eromoe** [comment]
@winer632 汗。。这readme里都写了， 出现这个问题就是因为`sh build.sh -DCOOKED` 执行了还不管用才回提的。。。。

事实上是报错不用管他， 加速实际上起作用了

**Comment by jiabing520a** [comment]
同时搬瓦工，一样的问题

**Comment by snooda** [comment]
不用管，不影响效果
