### ISSUE TITLE
使用net-speeder后，挂ss，dropbox上传速度被限制

### ISSUE THREAD

**Issue by vh2h** [snooda/net-speeder#34]
使用net-speeder之前，dropbox上传速度有4-5M/s，使用net-speeder之后，只有100K/s左右，搬瓦工，openvz, centOS6,按照教程来的，求解决方案。

**Comment by snooda** [comment]
发启动命令看下

**Comment by vh2h** [comment]
谢谢回答，我是小白，不知道你说的是不是./net_speeder venet0 “我的vps的ip”

**Comment by snooda** [comment]
./net_speeder venet0 tcp

**Comment by vh2h** [comment]
谢谢，改成你写的就好了吗？我是该直接执行你的命令，还是卸载了以后再重新安装再执行你的命令呢？该怎么卸载呢？谢谢

**Comment by vh2h** [comment]
你好，我重新装了一遍，按照你的指示，将启动命令换成了 ./net_speeder venet0 tcp  还是没有用， dropbox的上传速度还是下降了一个数量级。

**Comment by suixinio** [comment]
我同样也遇到了上传降速这个问题。
我的解决方案是使用bpf规则只复制本机发出的包

例如↓：
`./net_speeder venet0 "tcp and src host 本机 IP 地址" `
希望对你也有所帮助
