### ISSUE TITLE
centos6.5 卡在启动过程中

### ISSUE THREAD

**Issue by scream7** [snooda/net-speeder#35]
机器是bandwagon的128M内存配置
最后运行./net_speeder venet0 "ip"
会卡在 init libnet 这一行
请问如何解决？多谢

**Comment by Notarium** [comment]
我也遇到相同的问题了。。。

**Comment by tshu-w** [comment]
same issue on ubuntu

**Comment by scream7** [comment]
@NotA1994 @Voleking 
我记得后来我直接ping vps，是启动成功了，你们可以验证一下。

**Comment by StaticLove** [comment]
same problem on Centos 7

**Comment by tanpengsccd** [comment]
这个应该是 成功了，你试下

**Comment by snooda** [comment]
可以加&后台运行。这是一个常驻进程
