### ISSUE TITLE
不允许操作，是不可以用吗？

### ISSUE THREAD

**Issue by lbbboy** [snooda/net-speeder#36]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[60] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[72] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by btyh17mxy** [comment]
+1 centos 7

**Comment by joyoyao** [comment]
+2 centos 7

**Comment by klzsysy** [comment]
centos6 有这条信息 但使用正常

**Comment by gxcuit** [comment]
也出现了这一个问题

**Comment by jiabing520a** [comment]
+2 centos6

**Comment by snooda** [comment]
可以忽略，不影响效果
