### ISSUE TITLE
请问有人在vultr上安装成功吗？

### ISSUE THREAD

**Issue by krstina** [snooda/net-speeder#37]
全部安装完 ping 没有 DUP!
结束进程 显示没有这个进程

**Comment by syaofox** [comment]
vultr一切正常

**Comment by BadaDu** [comment]
vultr上一直报：err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)，系统debian 7 x64求大神帮忙 @krstina @syaofox @snooda

**Comment by bao3** [comment]
请依照你的系统不同，执行不同的指令，我是 Arch Linux @ Vultr ：

```
pacman -Sy ethtool
ethtool -K ens3 tx off
ethtool -K ens3 rx off
ethtool -K ens3 gso off
ethtool -K ens3 gro off

```

然后退出当前的登录终端（不是重启）重新建立 ssh 连线，再次尝试 net-speeder ens3 “ip” 。

我是用这个方式解决了。

> 在这个系统中我的 Vultr 的网卡是 ens3 
> 出现这个的原因就是 net-speeder  发送了一个巨大的数据包而不切分，超过了 MTU ，这个解包打包的工作是交给网卡来完成，所以我们关闭网卡的这个功能，改让系统来做这个工作，坏处就是增加了 CPU 负载
> 好处就是。。。我们可以用 net-speeder 了，而且真的有改观。

#15 两个属于同一个问题
😬

**Comment by bao3** [comment]
#15 同样的问题。

**Comment by mydansun** [comment]
@bao3 

root@xxxxxx:~# ethtool -K eth0 tx off
Actual changes:
tx-checksumming: off
        tx-checksum-ip-generic: off
tcp-segmentation-offload: off
        tx-tcp-segmentation: off [requested on]
        tx-tcp-ecn-segmentation: off [requested on]
        tx-tcp6-segmentation: off [requested on]
udp-fragmentation-offload: off [requested on]
root@xxxxxx:~# ethtool -K eth0 gso off
root@xxxxxx:~# ethtool -K eth0 gro off
root@xxxxxx:~# ethtool -K eth0 **rx** off
**Cannot change rx-checksumming**
**Could not change any device features**

请问这是什么问题啊。。谢谢！！我Ubuntu 15.10

另外，我运行了这些命令之后，运行就一直卡在**init libnet**，但是后面不会出现错误信息了，这是正常的么？

**Comment by bao3** [comment]
@mydansun ....那不是卡在 init libnet ，程序只能执行到这里，也就是说，你这个问题已经解决了。

**Comment by mydansun** [comment]
@bao3  但是我用linux的ping并没有看到重复包的标志啊

**Comment by bao3** [comment]
@mydansun  与此案无关。请检查其他问题。

**Comment by cha1n** [comment]
@bao3 

一样arch@vultr

pacman -Sy ethtool
ethtool -K ens3 tx off
ethtool -K ens3 rx off
ethtool -K ens3 gso off
ethtool -K ens3 gro off

之后还是有提示...

**Comment by wesley0314** [comment]
我是vultr centos7x64 error log 长这样，是网络设备填错了吗？
Device: venet0
Filter rule: ip
ethernet header len:[14](14:normal, 16:cooked)
Couldn't get netmask for device venet0: SIOCGIFADDR: venet0: No such device
init pcap
pcap_open_live dev:[venet0] err:[venet0: No such device exists (SIOCGIFHWADDR: No such device)]
init pcap failed

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by snooda** [comment]
关闭tso即可
