### ISSUE TITLE
如何知道netspeeder运行成功没成功？

### ISSUE THREAD

**Issue by icase** [snooda/net-speeder#4]
执行了之后，看进程里没有，是我执行错误还是只是一次性命令？

**Comment by 0cean** [comment]
ping一下主机ip，返回结果就可以看出。
Sent using CloudMagic
On 周二, 2月 24, 2015 at 4:29 上午, icase notifications@github.com wrote:执行了之后，看进程里没有，是我执行错误还是只是一次性命令？

**Comment by tanpengsccd** [comment]
top 命令 看 有没有net-speeder  这个进程。
然后再去youtube 试下能不能720P 流畅播放。
顺便可以看下下行速度能不能达到400-500K／s
