### ISSUE TITLE
安装遇到以下错误

### ISSUE THREAD

**Issue by terrytan95** [snooda/net-speeder#40]
net_speeder.c:1:18: 错误：pcap.h：没有那个文件或目录
net_speeder.c:8:20: 错误：libnet.h：没有那个文件或目录
net_speeder.c:21: 警告：‘struct pcap_pkthdr’在形参表内部声明
net_speeder.c:21: 警告：它的作用域仅限于此定义或声明，这可能并不是您想要的
net_speeder.c:37: 警告：‘struct pcap_pkthdr’在形参表内部声明
net_speeder.c:37: 错误：与‘got_packet’类型冲突
net_speeder.c:21: 附注：‘got_packet’的上一个声明在此
net_speeder.c: 在函数‘got_packet’中:
net_speeder.c:41: 错误：‘libnet_t’未声明(在此函数内第一次使用)
net_speeder.c:41: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
net_speeder.c:41: 错误：所在的函数内也只报告一次。)
net_speeder.c:41: 错误：‘libnet_handler’未声明(在此函数内第一次使用)
net_speeder.c:41: 错误：expected expression before ‘)’ token
net_speeder.c:46: 错误：提领指向不完全类型的指针
net_speeder.c:47: 错误：提领指向不完全类型的指针
net_speeder.c:48: 错误：提领指向不完全类型的指针
net_speeder.c:50: 错误：提领指向不完全类型的指针
net_speeder.c: 在文件层：
net_speeder.c:59: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘*’ token
net_speeder.c: 在函数‘main’中:
net_speeder.c:72: 错误：‘PCAP_ERRBUF_SIZE’未声明(在此函数内第一次使用)
net_speeder.c:73: 错误：‘pcap_t’未声明(在此函数内第一次使用)
net_speeder.c:73: 错误：‘handle’未声明(在此函数内第一次使用)
net_speeder.c:76: 错误：‘fp’的存储大小未知
net_speeder.c:77: 错误：‘bpf_u_int32’未声明(在此函数内第一次使用)
net_speeder.c:77: 错误：expected ‘;’ before ‘net’
net_speeder.c:91: 错误：‘net’未声明(在此函数内第一次使用)
net_speeder.c:91: 错误：‘mask’未声明(在此函数内第一次使用)
net_speeder.c:106: 错误：‘libnet_t’未声明(在此函数内第一次使用)
net_speeder.c:106: 错误：‘libnet_handler’未声明(在此函数内第一次使用)

**Comment by m13253** [comment]
少依赖 libpcap-dev
