### ISSUE TITLE
感谢snooda开源，用了之后般瓦工飞起来了，400k/s！

### ISSUE THREAD

**Issue by falconwoods** [snooda/net-speeder#41]
不知道500g的流量，够不够用

**Comment by pexcn** [comment]
一个月能超过200G你牛逼。。。

**Comment by osdebianly** [comment]
[别高兴太早了](https://github.com/snooda/net-speeder/issues/21#issuecomment-223479685)

**Comment by falconwoods** [comment]
3楼是不是朝廷派来的？我擦，我可是良民

**Comment by eromoe** [comment]
你是怎么装的？
ubuntu 搬瓦工  一堆人都这个错

```
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
```

**Comment by mengbingrock** [comment]
@eromoe 我的ubuntu系统也出现相同错误，然而似乎仍然可以感受到可观测到的加速。 可能是编译时出的问题。

**Comment by Chansie** [comment]
@eromoe 我今天也出现同样的错误

**Comment by Elgins** [comment]
我就问问能不能看youtube 720p视频，我依旧卡的一比

**Comment by SherlockLee** [comment]
@Elgins youtube 720p一开始会缓冲一阵儿,过一会儿就可以流畅的观看
