### ISSUE TITLE
搬瓦工运行错误调查，麻烦无错的朋友(需要使用搬瓦工)也报告一下 【针对错误-1 bytes written (Operation not permitted)】

### ISSUE THREAD

**Issue by eromoe** [snooda/net-speeder#43]
注意是

```
packet len:[64] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
```

不是 (错误内容不同)

```
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
```

本人是 搬瓦工 512M   ubuntu 14.04 x86（32位）
看到有的人搬瓦工都成功了，所以我想是不是系统的问题，比如是ubuntu的问题，或者32位64位的问题。
x86是 32位， x86_x64是64位

PS:曾经用过2次 finalspeed， 速度很快，能有500K以上，电信和长宽都可以，不过用一会会断，过了2天后fs就无法加速了（即使能连接上），所以另一种可能就是搬瓦工加上了限制

**Comment by csbzy** [comment]
搬瓦工 256M ubuntu 14.04 x86_64 也一样
`packet len:[17664] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
`

**Comment by eromoe** [comment]
@chenshaobo 
你这是 Message too long啊 ，用这个 `sh build.sh -DCOOKED` 编译 应该就能解决

**Comment by eromoe** [comment]
我突然间发现。。。。貌似出现这个错也没有问题，虽然访问网站慢，但是下载东西速度变快了很多。。。
我之前都是用speedtest 测试的，每次启动后速度都没有增加 所以还怀疑是没有起作用。。。

**Comment by eromoe** [comment]
刚刚专门找了个地址测试，貌似确实和报错无关

确实是开启后，下载东西的时候速度回变快很多
关闭后下载速度就变慢了，但是看网站的速度感觉没有变化。。。

**Comment by WarmColor** [comment]
同样的问题，之前的OS可以，新装了一个OS就报错了

**Comment by cvstore** [comment]
用 sh build.sh -DCOOKED 编译 ,在搬瓦工解决了 long message的问题。谢谢啦！
