### ISSUE TITLE
感谢开发者，加速效果太棒！！我是小白求问如何开机后台自动运行？

### ISSUE THREAD

**Issue by lbbboy** [snooda/net-speeder#44]
非常感谢~

**Comment by htgy** [comment]
echo ‘nohup /usr/bin/net_speeder venet0 “ip” >/dev/null 2>&1 &’ >> /etc/rc.local

**Comment by tanpengsccd** [comment]
楼上符号貌似有问题。
这个试试。
echo 'nohup /usr/bin/net_speeder venet0 "ip" >/dev/null 2>&1 &' >> /etc/rc.local

**Comment by tanpengsccd** [comment]
我的bandwagonhost貌似没效果，换成这样的才可以使用
需要root 权限
echo '/home/你的用户名/net_speeder venet0 "ip" ' >> /etc/rc.local

**Comment by prinnyk** [comment]
@tanpengsccd 应该是每个人存放netspeeder的路径不一样，改成自己的就好了，可以用ps -ef看一下有没有启动
