### ISSUE TITLE
error -1 bytes written (Bad address)

### ISSUE THREAD

**Issue by fengshens** [snooda/net-speeder#46]
centos6 i386
./net_speeder eth0 "ip"

packet len:[21451] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Bad address)
]
packet len:[24512] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Bad address)
]
packet len:[24123] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Bad address)
]

**Comment by guodage** [comment]
我也报这个错  不过貌似已经有效果了
