### ISSUE TITLE
是否有可能通过多开打到4倍发包呢？

### ISSUE THREAD

**Issue by skyburnoooomg** [snooda/net-speeder#47]
RT，有些地区网络确实不太好，电信丢包太太太严重了，所以只能考虑这样的办法提高速度。

**Comment by gqbre** [comment]
多次执行命令可以叠加的

**Comment by lyqblue** [comment]
我不小心执行了好几次，，现在倒是没有丢包，，，变成一次发送36个包，，top进程里有5个net_speeder,,,,怎么取消其他四个进程。。有懂得的的大佬没？

**Comment by gqbre** [comment]
@lyqblue 重启一下咯~ 就剩一个了233

**Comment by lyqblue** [comment]
@gqbre 重启不管用，后来整了一行代码：echo "killall net_speeder" >> /etc/rc.local，然后reboot后只有一个进程了，不过ping测试的时候，一次同时发送四个包，其中三个带（DUP!），正常是一次2包（其中一个带DUP！）是吧？大佬还有其他解决办法不~

**Comment by harbinbeer** [comment]
连接双方开启，就是4倍。

**Comment by snooda** [comment]
不会。最多双倍
