### ISSUE TITLE
TCP buffer size過大時, err msg (Message too long)而無法雙倍發包, 是否可以先分割?

### ISSUE THREAD

**Issue by kennylam777** [snooda/net-speeder#48]
分析過源碼, TCP的包在跑 net_speeder.c的 libnet_adv_write_raw_ipv4, 

例如 
`packet len:[13180] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)`

但如果控制TCP buffer size, 讓packet len小於MTU, 那就沒問題可以雙倍發

問題是, MTU再多也只有9K, 13180這種大小應該還有不少機會

**Comment by kennylam777** [comment]
找到暫時解決方法

https://github.com/snooda/net-speeder/issues/2

**Comment by willyloving** [comment]
packet len:[5800] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]，如何解决？

**Comment by wilhelmTian** [comment]
packet len:[2800] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
我也输出了同样的日志，楼主是否有解决办法呢

**Comment by cyriltian** [comment]
尝试了一下，关闭网卡打包功能转交系统可解，但会提高cpu和ram占用。
ethtool -K eth0 tx off
ethtool -K eth0 rx off
ethtool -K eth0 gso off
ethtool -K eth0 gro off

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by liuxyon** [comment]
> 尝试了一下，关闭网卡打包功能转交系统可解，但会提高cpu和ram占用。
> ethtool -K eth0 tx off
> ethtool -K eth0 rx off
> ethtool -K eth0 gso off
> ethtool -K eth0 gro off

不起作用
