### ISSUE TITLE
No package libnet available.是怎么回事？

### ISSUE THREAD

**Issue by FrankZhang002** [snooda/net-speeder#49]
运行“yum install libnet libpcap libnet-devel libpcap-devel”
之后显示“No package libnet available.”

![image](https://cloud.githubusercontent.com/assets/2623240/17261935/019e621e-560b-11e6-92e4-8679cbfd4435.png)

请问这是怎么回事？

**Comment by JimLee1996** [comment]
显然是镜像中找不到库文件，上网查查其他的替代吧

**Comment by cshanbo** [comment]
同样问题，网上也找不到源地址。。。。

**Comment by RiyadWu** [comment]
@FrankZhang002 
See #16

**Comment by fineday009** [comment]
See #16

**Comment by YuZhenKao** [comment]
可以试试更换镜像源   [阿里镜像源](http://mirrors.aliyun.com/help/centos)
求个国外能用的镜像源，我用的板瓦工，服务器在加拿大，用阿里的基本没网速
