### ISSUE TITLE
运行会有这个错误信息

### ISSUE THREAD

**Issue by hdstar2009** [snooda/net-speeder#5]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)

另外不能后台运行，一直前台？

**Comment by hdstar2009** [comment]
像下面这样是运行起来了吗？

root@webserver:~# ./net_speeder venet0 "ip"
Device: venet0
Filter rule: ip
ethernet header len:[16](14:normal, 16:cooked)
init pcap
init libnet
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[60] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[60] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[60] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by derekhe** [comment]
我也遇到相似的错误

**Comment by snooda** [comment]
@hdstar2009 可以使用nohup+&来后台运行。那个错误可以暂时忽略。不影响使用，后续会修复

**Comment by hdstar2009** [comment]
感谢回复，感觉这个对美国的一些便宜vps还是明显有效。不用的话vps所谓的500G月流量也只能是白话空头了。
希望snooda能改进下。

2015-03-17 11:59 GMT+08:00 snooda notifications@github.com:

**Comment by hdstar2009** [comment]
这两天使用过程发现一个现象：就是看youtube视频（估计平时上网也是），用了netspeeder的美国vps似乎会停止发包，这时候youtube视频会停止转圈，一直不会有数据更新，如果拖动youtube播放条到其他位置，就可能重新数据传输了。

在 2015年3月18日 上午12:31，Itsme_ up hdstar2009@gmail.com写道：

**Comment by bluemoonn** [comment]
您好  该如何把这个加入到系统 启动里面呢

**Comment by hdstar2009** [comment]
把下面这行放到/etc/rc.local里面（如果是debian系统要放到exit 0上面）
nohup /root/net_speeder venet0 "ip" >/dev/null 2>&1 &

2016-04-19 18:54 GMT+08:00 tony notifications@github.com:
