### ISSUE TITLE
多個端口加速

### ISSUE THREAD

**Issue by aaronchin** [snooda/net-speeder#52]
請問 現在給多個端口加速要使用 src port xx or src port oo or src portyy 是否能使用 src port 12345-12378 這種方式?

**Comment by afc** [comment]
这个程序调用pcap的函数来过滤语法的
所以你可以查相关BPF语法 不过你可以用
```
./net_speeder venet0 "src portrange port1-port2"
```
来过滤指定源端口号范围

更多过滤语法参考[这里](https://biot.com/capstats/bpf.html)
