### ISSUE TITLE
搬瓦工安装就报错：net_speeder.c: In function 'got_packet':

### ISSUE THREAD

**Issue by piaoyun** [snooda/net-speeder#54]
net_speeder.c:1:18: error: pcap.h: No such file or directory
net_speeder.c:8:20: error: libnet.h: No such file or directory
net_speeder.c:21: warning: 'struct pcap_pkthdr' declared inside parameter list
net_speeder.c:21: warning: its scope is only this definition or declaration, which is probably not what you want
net_speeder.c:37: warning: 'struct pcap_pkthdr' declared inside parameter list
net_speeder.c:37: error: conflicting types for 'got_packet'
net_speeder.c:21: note: previous declaration of 'got_packet' was here
net_speeder.c: In function 'got_packet':
net_speeder.c:41: error: 'libnet_t' undeclared (first use in this function)
net_speeder.c:41: error: (Each undeclared identifier is reported only once
net_speeder.c:41: error: for each function it appears in.)
net_speeder.c:41: error: 'libnet_handler' undeclared (first use in this function)
net_speeder.c:41: error: expected expression before ')' token
net_speeder.c:46: error: dereferencing pointer to incomplete type
net_speeder.c:47: error: dereferencing pointer to incomplete type
net_speeder.c:48: error: dereferencing pointer to incomplete type
net_speeder.c:50: error: dereferencing pointer to incomplete type
net_speeder.c: At top level:
net_speeder.c:59: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
net_speeder.c: In function 'main':
net_speeder.c:72: error: 'PCAP_ERRBUF_SIZE' undeclared (first use in this function)
net_speeder.c:73: error: 'pcap_t' undeclared (first use in this function)
net_speeder.c:73: error: 'handle' undeclared (first use in this function)
net_speeder.c:76: error: storage size of 'fp' isn't known
net_speeder.c:77: error: 'bpf_u_int32' undeclared (first use in this function)
net_speeder.c:77: error: expected ';' before 'net'
net_speeder.c:91: error: 'net' undeclared (first use in this function)
net_speeder.c:91: error: 'mask' undeclared (first use in this function)
net_speeder.c:106: error: 'libnet_t' undeclared (first use in this function)
net_speeder.c:106: error: 'libnet_handler' undeclared (first use in this function)

请问下这个是什么问题呢？

**Comment by shadyfengl** [comment]
请问解决了吗

**Comment by WuYifanX** [comment]
中间步骤替换
 yum install -y libnet libpcap libnet-devel libpcap-devel

加上这个-y再试试

**Comment by qylixin** [comment]
yum install -y wget
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/libnet-devel-1.1.6-7.el6.i686.rpm
rpm -ivh libnet-devel-1.1.6-7.el6.i686.rpm

**Comment by code1303009** [comment]
搞定了么 我也是这个问题
