### ISSUE TITLE
一键脚本地址出错了，麻烦修正

### ISSUE THREAD

**Issue by hackant** [snooda/net-speeder#55]
--2016-12-09 03:07:43--  http://net-speeder.googlecode.com/files/net_speeder-v0.1.tar.gz
Resolving net-speeder.googlecode.com... 173.194.202.82, 2607:f8b0:400e:c00::52
Connecting to net-speeder.googlecode.com|173.194.202.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-09 03:07:43 ERROR 404: Not Found.

**Comment by DevDavid1307** [comment]
+1

**Comment by UranusCEO** [comment]
+1

**Comment by snooda** [comment]
话说一键脚本并不是我写的。。。。可以联系脚本作者
