### ISSUE TITLE
Mac一直卡在init libnet

### ISSUE THREAD

**Issue by saber1024** [snooda/net-speeder#56]
Saber@SaberdeMacBook-Pro ~$ sudo -s
Password:
root@SaberdeMacBook-Pro ~# ./net_speeder en0 "ip"

这样我不确定有没有问题因为网卡名称在设备管理器里是en0，

一直是这样
Device: en0
Filter rule: ip
ethernet header len:[14](14:normal, 16:cooked)
init pcap
init libnet

**Comment by afc** [comment]
[net_speeder.c](https://github.com/snooda/net-speeder/blob/master/net_speeder.c)的105至110行是用于初始化libnet
没提示你"init libnet failed"就说明成功了

你可以使用
```
./net_speeder venet0 "ip" &
```
来让net_speeder后台运行
