### ISSUE TITLE
大神、这么算成功吗？还有个问题。怎么设置开机自动启动

### ISSUE THREAD

**Issue by alstarking** [snooda/net-speeder#57]
[root@localhost net-speeder-master]# ./net_speeder venet0 "ip"
Device: venet0
Filter rule: ip
ethernet header len:[16](14:normal, 16:cooked)
init pcap
init libnet
packet len:[40] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by alstarking** [comment]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[40] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[40] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[70] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]

**Comment by guodage** [comment]
我也是这样，感觉没啥变化

**Comment by harbinbeer** [comment]
echo 'net_speeder venet0 "ip"' >> /etc/rc.local
