### ISSUE TITLE
执行./nets_peeder venet0 “ip”出错

### ISSUE THREAD

**Issue by cyriltian** [snooda/net-speeder#58]
Device: venet0
Filter rule: ip
ethernet header len:[14](14:normal, 16:cooked)
Couldn't get netmask for device venet0: SIOCGIFADDR: venet0: No such device
init pcap
pcap_open_live dev:[venet0] err:[venet0: No such device exists (SIOCGIFHWADDR: No such device)]
init pcap failed
望赐教，谢谢！

**Comment by Yprolic** [comment]
Couldn't get netmask for device venet0: SIOCGIFADDR: venet0: No such device
没找到名为venet0的网卡，你去ifconfig下网卡名，可能是eth0之类的

**Comment by bengxy** [comment]
ifconfig查看你的网卡名，你看对应你ip的那个网卡。
