### ISSUE TITLE
到底应该是venet0:0还是venet0

### ISSUE THREAD

**Issue by coffilk** [snooda/net-speeder#6]
我的搬瓦工openvz有两个网卡，venet0对应127.0.0.2 venet0:0对应公网ip 到底应该是用哪个，还是两个一起用？

**Comment by snooda** [comment]
直接venet0即可

**Comment by xlplbo** [comment]
我的venet0的IP是127.0.0.1,venet0:0是公网IP，要对那个网卡使用net_speeder,为什么？

**Comment by allenkey666** [comment]
两个都可以，效果一样

**Comment by Y2zz** [comment]
为毛我的报错
packet len:[17664] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]

**Comment by hyhy01** [comment]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
我是这样

**Comment by hyhy01** [comment]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[52] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
packet len:[40] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Operation not permitted)
]
