### ISSUE TITLE
实际消耗为3倍

### ISSUE THREAD

**Issue by hyjtool** [snooda/net-speeder#60]
搬瓦工现在用了加速确实不错，没用kcptun或者finalspeed多用一个客户端不爽。经反复测试实际消耗为3倍

**Comment by phlips5437** [comment]
请问楼上，这个3倍的话，假定我只看youtube，那么我每个月1T的流量扣除系统开销外，只相当于每个月300多G的实际可用流量嘛？

**Comment by hyjtool** [comment]
是的
