### ISSUE TITLE
运行一段时间后出现killed

### ISSUE THREAD

**Issue by LanHao0** [snooda/net-speeder#68]
ubuntu 14.04
加速有效果，但是……运行一段时间就会出现killed

**Comment by dulei0508** [comment]
就是啊，这是怎么造成的，是BUG吗？

**Comment by LanHao0** [comment]
可能是因为我主机内存小？512MB。

**Comment by dulei0508** [comment]
512M不小了吧，

**Comment by TangYang798** [comment]
我也是这个情况，没有什么错误提示。
512的机子，但是剩余内存300多。

**Comment by iosmanthus** [comment]
调试无果, 只要在大流量情况下容易崩溃 情况未知 我还在继续调试 尽量查明

**Comment by iosmanthus** [comment]
尝试换了一个主机系统之后 大流量环境不再有问题 原因不明 原来是在`Ubuntu 16.04 x86_64`  现在在 `Debian 8 x86_64` @LanHao0

**Comment by LanHao0** [comment]
@OsmanthusTree 
请问你换的系统是？

**Comment by NKUCodingCat** [comment]
Debian 8.0 x86_64  和 CentOS 7 x86_64在OVZ下都不行 @iosmanthus 你是KVM还是OVZ....
ubuntu 1204 x86_64 和 centOS 6 x86_64也不行。。。

**Comment by iosmanthus** [comment]
@NKUCodingCat   KVM

**Comment by iosmanthus** [comment]
OVZ就用bbr啦..

**Comment by NKUCodingCat** [comment]
我觉得的我找到解决方案了
只要吧net_speeder的executable file名字改掉就行了
既然OVZ这是靠名字kill的话。。。随便什么名字都可以了w

**Comment by LitchiCherry** [comment]
目前来看，搬瓦工会kill进程，尤其在流量较大的情况下，没流量可能不管你

**Comment by willduan** [comment]
mark

**Comment by NKUCodingCat** [comment]
@solologo =。=我改了executable以后这么久还没被kill过。。。

**Comment by koolwiki** [comment]
我也遇到这个问题，改名后几分钟还是被killed了
PS:刚才试着把netspeeder目录名字也改一下，整个目录都不出现netspeeder后稳定运行了一段时间。

**Comment by iosmanthus** [comment]
估计是正则匹配....
