### ISSUE TITLE
centos6_64上编译报错如下，是搬瓦工的VPS

### ISSUE THREAD

**Issue by cundi** [snooda/net-speeder#7]
内核版本
Linux django-web.ml 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

net_speeder.c:8:20: 错误：libnet.h：没有那个文件或目录
net_speeder.c: 在函数‘got_packet’中:
net_speeder.c:41: 错误：‘libnet_t’未声明(在此函数内第一次使用)
net_speeder.c:41: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
net_speeder.c:41: 错误：所在的函数内也只报告一次。)
net_speeder.c:41: 错误：‘libnet_handler’未声明(在此函数内第一次使用)
net_speeder.c:41: 错误：expected expression before ‘)’ token
net_speeder.c:46: 错误：提领指向不完全类型的指针
net_speeder.c:47: 错误：提领指向不完全类型的指针
net_speeder.c:48: 错误：提领指向不完全类型的指针
net_speeder.c:50: 错误：提领指向不完全类型的指针
net_speeder.c: 在文件层：
net_speeder.c:59: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘*’ token
net_speeder.c: 在函数‘main’中:
net_speeder.c:106: 错误：‘libnet_t’未声明(在此函数内第一次使用)
net_speeder.c:106: 错误：‘libnet_handler’未声明(在此函数内第一次使用)

**Comment by snooda** [comment]
没有装libnet-devel  可以参考readme里面的安装方法

**Comment by cundi** [comment]
好吧。自己解决了。按照Readmed来装才报这个错的。应该是搬瓦工repo里没有提供libnet的源。
谷歌搜了下，到这个网站http://rpm.pbone.net/ 手动下载RPM安装才解决的。

**Comment by ilaotan** [comment]
sudo yum install epel-release 然后在安装libnet-devel

**Comment by harrydleung** [comment]
你都没有装好libnet那些吧

**Comment by QinanWu** [comment]
@cundi 请问手动下载RPM，操作步骤是怎样的？

**Comment by qylixin** [comment]
yum install -y wget
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/libnet-devel-1.1.6-7.el6.i686.rpm
rpm -ivh libnet-devel-1.1.6-7.el6.i686.rpm
