### ISSUE TITLE
net_speeder 和BBR能共存吗？还是有BBR就不需要net_speeder？

### ISSUE THREAD

**Issue by tianlichunhong** [snooda/net-speeder#70]
net_speeder 和BBR能共存吗？还是有BBR就不需要net_speeder？

**Comment by pexcn** [comment]
可以，但没必要

**Comment by wjk199511140034** [comment]
可以，我的主机走gtt线路。每晚高峰期丢包率在30%左右，用 Crontab设置netspeeder每天19:00~3:00启动

**Comment by ganyanchuan1989** [comment]
我自己简单测试过，加了net_speeder 有点用。fast.com测试，由1M左右变成3M左右。fast.com 测试不知道有没有意义？
