### ISSUE TITLE
提示err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)

### ISSUE THREAD

**Issue by mazechi** [snooda/net-speeder#71]
packet len:[24757] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
packet len:[52378] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
packet len:[31916] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
packet len:[22813] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
packet len:[62287] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)
]
packet len:[24758] actual write:[-1]
err msg:[libnet_write_raw_ipv4(): -1 bytes written (Message too long)

一直报这个错，速度好像没怎么提升，系统是CentOS6.8 X86_64，带BBR，搬瓦工的KVM。

尝试过下面这个操作，好像没啥用。
ethtool -K eth0 tx off
ethtool -K eth0 rx off
ethtool -K eth0 gso off
ethtool -K eth0 gro off

**Comment by kid1412z** [comment]
ubuntu16.04LTS也报相同的错误

**Comment by ecjtu-YangkaiLin** [comment]
centos7出现同样的错误，有BBR

**Comment by yyuurrii34** [comment]
我想到一个最简单的解决办法，这种情况你把mtu阈值改大点不就完了，具体改多大，看你报错的文件大小而定。
`ifconfig 网卡名 mtu 多大数 up`

**Comment by NKUCodingCat** [comment]
@yyuurrii34 确实管用。。。但是我觉得似乎会导致性能问题。。。【测了一下速度

**Comment by snooda** [comment]
关闭tso即可，已更新方式
