### ISSUE TITLE
net-speeder可以加速ipv6吗

### ISSUE THREAD

**Issue by willduan** [snooda/net-speeder#75]
如题，感觉加速ipv4挺好的，但是ipv6加速没有感觉出来，想请教一下有ipv6加速吗？
我使用的命令是：
```
sudo net-speeder-master/net_speeder venet0 "ip"
```
谢谢各位。

**Comment by snooda** [comment]
没有试过，可以tcpdump在客户端抓包看一下能否收到双倍

**Comment by koolwiki** [comment]
我试了加速不了ipv6，不知道要怎样修改一下？

**Comment by juvechina** [comment]
https://github.com/juvechina/net-speeder/tree/master 支持了
