### ISSUE TITLE
到底是ip还是"ip"

### ISSUE THREAD

**Issue by wjk199511140034** [snooda/net-speeder#78]
添加开机启动
`echo "nohup /usr/local/net_speeder/net_speeder eth0 "ip" >/dev/null 2>&1 &" >> /etc/rc.local`
实验了一下好像没有效果
无意间看到/etc/rc.local里面的启动命令
`nohup /usr/local/net_speeder/net_speeder eth0 ip >/dev/null 2>&1 &`
ip的引号没有了，影响使用吗？
还有怎么看netspeeder到底在加速哪个端口？ps -aux只能看到在运行，无法看到更详细的信息了

**Comment by pexcn** [comment]
"ip"

**Comment by snooda** [comment]
两种写法都可以。
kvm下有bug，已经修复了
